### ISSUE TITLE
Python 3.7 compatibility changes

### ISSUE THREAD

**Issue by jamenlang** [rany2/edge-tts#403]
I know it's not a huge priority, but this doesn't work with Python 3.7 just because of Literal and the way it's imported.

ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)

adding this to communicate, typing and data_classes fixes the project for Python 3.7

```
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
```
